import { Router } from "express";
import { login, register, logout, updateMe } from "../controllers/authController.js";
import { validate, schemas } from "../utils/validate.js";
import { requireAuth } from "../utils/auth.js";
const r = Router();
r.post("/register", validate(schemas.register), register);
r.post("/login", validate(schemas.login), login);
r.post("/logout", logout);
r.put("/me", requireAuth, validate(schemas.updateMe), updateMe);
export default r;
